# -*- coding: utf-8 -*-

from . import models
from . import sale
from . import res_partner
from . import res_users
from . import sales_admin
from . import account_move
from . import sale_make_invoice_advance
from . import stock_picking
from . import mrp_production
from . import cancel_sq_memory
from . import reason_cancellation
from . import purchase
from . import daily_report
from . import daily_report_memory
from . import leads_followup_xlsx
from . import daily_report_xlsx
from . import customer_complain
from . import leads_project
from . import followup_leads_project
from . import contact_person
from . import leads_followup_memory
from . import confirm_leads_followup_memory
from . import create_contact_memory
from . import stock_move
from . import mrp_workorder_line
from . import additional_product_mrp_production
from . import proof_of_payment